---
apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: postgres
type: Opaque
data:
  username: bGlsdXNlcg==
  password: bGlua2VkaW4=
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: spring-kube
  namespace: postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: lil
      owner: liluser
      secret:
        name: database-secret
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  5432: postgres/spring-kube-rw:5432
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spring-kube-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": spring-kube
  podMetricsEndpoints:
  - port: metrics